### ISSUE TITLE
Weapon Damage Multiplier issue

### ISSUE THREAD

**Issue by NickKolowski** [teloric/PathfinderCharacterSheet#2]
In the weapons section, there is a section to multiply your stat modifier, for example using a two handed weapon does 1.5 times the strength mod. The problem is that this multiplier is being applied to both hit and damage while it should only be applied to damage for two handed weapon use.

If you want to generalize it for both to-hit and damage rolls, it's probably best to split them into separate fields.

**Comment by teloric** [comment]
Found and fixed the problem
